// Źródło: https://kwejk.pl/obrazek/3454065/wypowiedzi-korwina-generator20.html
//„”
//teksty
let data = {
  p: [
    // Zwrócenie uwagi odbiorcy do siebie
    "Prosze zwrócić uwage, że",
    "I tak mam trzy razy mniej czasu, więc prosze mi pozwolić powiedzieć",
    "Państwo sie śmieją, ale",
    "Ja nie potrzebowałem edukacji seksualnej, żeby wiedzieć, że",
    "No niestety:",
    "Gdzie leży przyczyna problemu? Ja Państwu powiem:",
    "Państwo chyba nie wiedzą, że",
    "Oświadczam kategorycznie:",
    "Powtarzam:",
    "powiedzmy to z całą mocą:",
    "W Polsce dzisiaj",
    "Państwo sobie nie zdają sprawy, że",
    "To ja przepraszam bardzo:",
    "Otóż nie wiem, czy pan wie, że",
    "Yyyyy...",
    "Ja chce powiedzieć jedną rzecz:",
    "Trzeba to powiedzieć jasno:",
    "Jakby to powiedział wybitny krakowianin Stanisław Lem",
    "Prosze mnie dobrze zrozumieć:",
    "Ja chciałem państwu przypomnieć, że",
    "Niech państwo nie mają złudzeń:",
    "Powiedzmy to wyraźnie:",
    "musimy jasno i stanowczo powiedzieć naszym kobietom, starcom i dzieciom:",
    "Dla wyjaśnienia moim wyborcom:",
    "Z największą przyjemnością stanę przed sądem, dlatego, że ktoś musi powiedzieć prawdę:",
    "Powiedzmy sobie jasno:",
    "Według opinii własnych zwolenników",
    "Pisząc wprost:",
    "Mówiąc wprost",
    "Tak - konstytucja ZSRR wyraźnie mówiła, że",
    "Jakiś nawiny rosjanin dziwi się, że",
    "Jak to napisałem wiele razy (ale kto dziś czyta?) -",
    "Komentarze: ",
    "Myślcie jak POLITYCY, a nie jak małe DZIECI bojące sie niedźwiedzia -",
    "Niedawno",
  ],
  d: [
    //Cel obrażania
    "Kobiety, które zawsze udają",
    "właściciele niewolników",
    "Związkowcy",
    "Trockliści",
    "tak zwane dzieci kwiaty",
    "rozmaici urzędnicy",
    "federaści",
    "etatyści",
    "ci durnie i złodzieje",
    "ludzie wybrani głosami meneli spod budki z piwem",
    "socjaliści pobożni",
    "socjaliści bezrobotni",
    "komuniści z krzyżem w zębach",
    "agenci obcych służb",
    "członkowie Bandy Czworga",
    "pseudo-masoni z Wielkiego Wschodu Francji",
    "przedstawiciele czerwonej hołoty",
    "ci wszyscy - tfu! - geje",
    "funkcjonariusze reżymowej telewizji",
    "tak zwani ekolodzy",
    "ci wszyscy - tfu! - demokranci",
    "agenci bezpieki",
    "feminazistki",
    "feministki",
    "czterech milionów czarnych",
    "ludzie Epoki Telewizyjnej",
    "anarchiści",
    "katolicy",
    "banda komuchów",
    "ci z PO",
    "republiki związkowe",
    "ambasadarowie obcych miast",
    "Ukraińcy",
    "Anglo-sasowie",
    "kobiety",
    "ONZ",
  ],
  t: [
    //co myśli o tej grupie
    'po przeczytaniu "Manifestu Komunistycznego"',
    "którymi się brzydze",
    "których nienawidze",
    'z okolic "Gazety Wyborczej"',
    "czyli taka żydokomuna",
    "odkąd zniesiono kare śmierci",
    "którymi pogardzam",
    "których miejsce w normalnym kraju jest w więzieniu",
    "na polecenie Brukseli",
    "posłusznie",
    "bezmyślnie",
    "z nieprawdopodobną pogardą dla człowieka",
    "za pieniądze podatników",
    "zgodnie z ideologią LGBTQZ",
    "za wszelką cene",
    "zupełnie bezkarnie",
    "całkowicie bezczelnie",
    "o poglądach na lewo od komunizmu",
    "celowo i świadomie",
    "z premedytacją",
    "którym odebrałbym prawo wyborcze,",
    "czyli banda chamów importowanych z zagranicy,",
    "którzy powinni działać zgodnie z elementarzem: „Gdy chcesz zniszczyć organizację wybieraj niezadowolonych”, lecz by to osiągnąć to",
    "na których niemarnowałbym ostrej amunicji",
    "taka bandycka instytucja",
    "którzy domagaliby sie zasiłków socjalnych od państwa",
    'ogłupieni na dzisiejszych "renomowanych" uniwersytetach',
    "którzy są bardziej na lewo niż SLD",
    "czyli taka partia liberalna",
    "którzy mają tyle samo wspólnego z JE Włodzimierzem Putinem",
    "za pieniądze arabskich emirów",
    "wychwalani przez obecny reżym",
    "zamiast rozwiązywania w zaciszu gabinetów prawdziwych problemów",
  ],
  c: [
    //co robią
    "udają homoseksualistów",
    "niszczą rodzinę",
    "idą do polityki",
    "zakazują góralom robienia oscypków",
    "organizują paraolimpiady",
    "wprowadzają ustrój, w którym raz na cztery lata można wybrać sobie pana",
    "ustawiają fotoradary",
    "wprowadzają dotacje",
    "wydzielają buspassy",
    "podnoszą wiek emerytalny",
    "rżną głupa",
    "odbierają dzieci rodzicom",
    "wprowadzają absurdalne przepisy",
    "umieszczają dzieci w szkołach koedukacyjnych",
    "wprowadzają parytety",
    "nawołują do podniesienia podatków",
    "próbują wyrzucić kierowców z miast",
    "próbują skłócić Polske z Rosją",
    "głoszą brednie o globalnym ociepleniu",
    "zakazują posiadania broni",
    "nie dopuszczają prawicy do władzy",
    "uczą dzieci homoseksualizmu",
    "chcą dopuścić kobiety do władzy",
    "chcą dać kobietom prawa",
    "odbierają obywatelom prawo do obrony",
    "walczą o prawo do zawierania „homo-małżeństw”",
    "wprowadzają ustawy przez które miałoby się zabijać więcej nienarodzonych dzieci,",
    "chcą zniszczyć Porządek Cywilny",
    "kradli, ale i pozwalają kraść",
    "dobierają sobie Biernych, Miernych ale Wiernych",
    "znakomicie potrafią grać na uczuciach L**u robiąc mądre miny i umiejętnie wykorzystując zestawy słów, które nic nie znaczą",
  ],
  i: [
    //dlaczego to robią
    "żeby poddawać wszystkich tresurze",
    "bo taka jest ich natura",
    "bo chcą wszystko kontrolować",
    "bo nie rozumieją, że socjalizm nie działa",
    "żeby wreszczie zapanował socjalizm",
    "dokładnie tak jak towarzysz Janosik",
    "zamiast pozwolić ludziom zarabiać",
    "żeby wyrwać kobiety z domu",
    "bo to jest w interesie tak zwanych ludzi pracy",
    "zamiast pozwolić decydować konsumentowi",
    "żeby nie opłacało sie mieć dzieci",
    "zamiast obniżyć podatki",
    "bo nie rozumieją, że selekcja naturalna jest czymś dobrym",
    "żeby mężczyźni przestali być agresywni",
    "bo dzięki temu mogą kraść",
    "bo dostają za to pieniądze",
    "bo tak sie uczy w państwowej szkole",
    "bo bez tego (tfu!) demokracja nie może istnieć",
    "bo głupich jest więcej niż mądrych",
    "bo chcą stworzyć raj na ziemii",
    "bo chcą zniszczyć cywilizacje białego człowieka",
    "bo takie jest prawo czarnego rynku",
    "bo nie widzą świata takim jaki jest,tylko takim jakim im go pokażą",
    "bo na tym polega liberalizm.",
    "Żeby nas potem powybierać jak ryby z saka",
    "aby obniżyć poziom edukacji",
    "bo chcą Prawa Człowieka na ich korzyść",
    "ponieważ natężenie mikkofobii na linijkę przekroczyło normy europejskie",
    "bo to są ciemniacy z dyplomami",
    "bo oni twerdzą, za ś.tow.Józefem Goebbelsem, że prawdę można zrobić z każdego kłamstwa, byle je sto razy powtórzyć",
    "bo obawiają się, że mądrzejsi od nich mogą ich obalić",
    '- a "obywatele" nie mają żadnej nadzieji',
  ],
  s: [
    //zakończenie
    "co ma zresztą tyle samo sensu, co zawody w szachach dla debili.",
    "co zostało dokładnie zaplanowane w Magdalence przez świętej pamięci Genereała Kiszczaka.",
    "i trzeba być idiotą, żeby ten system popierać.",
    "ale nawet ja jeszcze dożyje normalnych czasów.",
    "co dowodzi, że wyskrobano nie tych, co trzeba.",
    'a zwykłym ludziom wmawiają że im coś "dadzą".',
    "- cóż: chcieliście - tfu! - demokracji to macie.",
    "dlatego trzeba zlikwidować koryto a nie zmieniać świnie.",
    "a wystarczyłoby przestać wypłacać zasiłki.",
    "podczas gdy biali ludzie uważani są za dziwaków.",
    "co w wieku XIX po prostu by wyśmiano.",
    "- dlatego w społeczeństwie jest równość, a powinno być rozwarstwienie.",
    "ale w wolnej Polsce pójdą siedzieć.",
    "przez kolejne kadencje.",
    "o czym sie nie mówi.",
    "i dlatego właśnie Europa umiera.",
    "ale przyjdą muzułmanie i zrobią porządek.",
    "- tak samo zresztą jak za Hitlera.",
    "- prosze zobaczyć, co sie dzieje na Zachodzie, jeśli państwo nie wierzą.",
    "co lat temu sto nikomu nie przyszłoby do głowy.",
    "Lud jest głupi jak but z lewej stopy.",
    "jest to dużo bardziej zasadne niż edukacja seksualna młodzieży.",
    "a powinno być to z całą surowością karane.",
    "przed czym zresztą ostrzegaliśmy już w 1980 r.",
    "ale pamiętajmy, podobno każdy za młodu powinien być socjalistą, a potem mądrzeje.",
    "Trzeba być idiotą, żeby chcieć w takim ustroju żyć.",
    "ma to tyle-ż sensu, co kojarzenie chrześcijaństwa z wojnami krzyżowymi.",
    "jest to pewna ideologia, po stokroć groźniejsza niż całe Imperium Zła.",
    "a jutro posuną się o krok dalej.",
    "ale to oznacza, że Murzyni niedługo podbiją świat. I wyrżną nas.",
    "to za trudne dla IDIOTÓW z Brukseli.",
    "- Włodzimierz Putin ściągnie z tego podatek i kupi jakąś rakietę do walenia w Ukraińców.",
    "i właśnie dlatego Polacy to ciemniacy i ksenofobowie - ale za to ludzie szczęśliwi.",
    "rozumiem, że Wołyń mają na myśli?",
    "- Należy natychmiast zaorać tą reżimową tubę i sprywatyzować - natychmiast!",
    'które przecież są jak powszechnie wiadomo, "szkodliwe".',
    "- najwyższy czas na Kontrrewolucje!",
    "to na pewno Putin. Albo CIA...",
    "ale sanatorzy wyznawali Teorię dwóch wrogów.",
    "- to wszystko jest teatr stworzony przy okrągłym stole.",
    "- przed czym chcecie ludzi zniechęcić, utrzymując dalej podatek dochodowy?",
    "tę włąśnie praktykę zwalczam.",
    "ale dzisiejsza dzicz nie uznaje zasad europejskich zasad moralnych.",
    "ale po tej wypowiedzi nie powinni pokazywać sie publicznie ze wstydu.",
    "#RządRżnieGłupa!",
    "ciekawe co obstawiają bookmacherzy.",
    "Bądźmy w końcu wolni! Precz z socjalizmem!",
    "czy feministki nadal chcą równych praw?",
    "Ludzie: nauczcie sie dodawać 2 do 2.",
    "póki nie zmienimy ustroju na normalny to nic sie nie poprawi.",
  ],
};

/*
Nie wiem gdzie te dodać : 
- "wyrządza to Polsce szkody, bo polityk nie powinien kierować sie uczuciami, lecz racją stanu",
- ""
*/
