// Źródło: https://kwejk.pl/obrazek/3454065/wypowiedzi-korwina-generator20.html
//„”
//teksty
let data = {
    "p": [
      // Zwrócenie uwagi odbiorcy do siebie
      "Prosze zwrócić uwage, że",
      "I tak mam trzy razy mniej czasu, więc prosze mi pozwolić powiedzieć",
      "Państwo sie śmieją, ale",
      "Ja nie potrzebowałem edukacji seksualnej, żeby wiedzieć, że",
      "No niestety:",
      "Gdzie leży przyczyna problemu? Ja Państwu powiem:",
      "Państwo chyba nie wiedzą, że",
      "Oświadczam kategorycznie:",
      "Powtarzam:",
      "powiedzmy to z całą mocą:",
      "W Polsce dzisiaj",
      "Państwo sobie nie zdają sprawy, że",
      "To ja przepraszam bardzo:",
      "Otóż nie wiem, czy pan wie, że",
      "Yyyyy...",
      "Ja chce powiedzieć jedną rzecz:",
      "Trzeba to powiedzieć jasno:",
      "Jakby to powiedział wybitny krakowianin Stanisław Lem",
      "Prosze mnie dobrze zrozumieć:",
      "Ja chciałem państwu przypomnieć, że",
      "Niech państwo nie mają złudzeń:",
      "Powiedzmy to wyraźnie:",
      "musimy jasno i stanowczo powiedzieć naszym kobietom, starcom i dzieciom:",
      "Dla wyjaśnienia moim wyborcom:",
      "Z największą przyjemnością stanę przed sądem, dlatego, że ktoś musi powiedzieć prawdę:",
      "Powiedzmy sobie jasno:",
    ],
    "d": [
      //Cel obrażania
      "Kobiety, które zawsze udają",
      "właściciele niewolników",
      "Związkowcy",
      "Trockliści",
      "tak zwane dzieci kwiaty",
      "rozmaici urzędnicy",
      "federaści",
      "etatyści",
      "ci durnie i złodzieje",
      "ludzie wybrani głosami meneli spod budki z piwem",
      "socjaliści pobożni",
      "socjaliści bezrobotni",
      "komuniści z krzyżem w zębach",
      "agenci obcych służb",
      "członkowie Bandy Czworga",
      "pseudo-masoni z Wielkiego Wschodu Francji",
      "przedstawiciele czerwonej hołoty",
      "ci wszyscy - tfu! - geje",
      "funkcjonariusze reżymowej telewizji",
      "tak zwani ekolodzy",
      "ci wszyscy - tfu! - demokranci",
      "agenci bezpieki",
      "feminazistki",
      "feministki",
      "czterech milionów czarnych",
      "ludzie Epoki Telewizyjnej",
      "anarchiści",
      "katolicy",
      "banda komuchów",
    ],
    "t": [
      //co myśli o tej grupie
      "po przeczytaniu \"Manifestu Komunistycznego\"",
      "którymi się brzydze",
      "których nienawidze",
      "z okolic \"Gazety Wyborczej\"",
      "czyli taka żydokomuna",
      "odkąd zniesiono kare śmierci",
      "którymi pogardzam",
      "których miejsce w normalnym kraju jest w więzieniu",
      "na polecenie Brukseli",
      "posłusznie",
      "bezmyślnie",
      "z nieprawdopodobną pogardą dla człowieka",
      "za pieniądze podatników",
      "zgodnie z ideologią LGBTQZ",
      "za wszelką cene",
      "zupełnie bezkarnie",
      "całkowicie bezczelnie",
      "o poglądach na lewo od komunizmu",
      "celowo i świadomie",
      "z premedytacją",
      "którym odebrałbym prawo wyborcze,",
      "czyli banda chamów importowanych z zagranicy,",
      "którzy powinni działać zgodnie z elementarzem: „Gdy chcesz zniszczyć organizację wybieraj niezadowolonych”, lecz by to osiągnąć to",
      "na których niemarnowałbym ostrej amunicji",
      "taka bandycka instytucja",
      "którzy domagaliby sie zasiłków socjalnych od państwa",
    ],
    "c": [
      //co robią
      "udają homoseksualistów",
      "niszczą rodzinę",
      "idą do polityki",
      "zakazują góralom robienia oscypków",
      "organizują paraolimpiady",
      "wprowadzają ustrój, w którym raz na cztery lata można wybrać sobie pana",
      "ustawiają fotoradary",
      "wprowadzają dotacje",
      "wydzielają buspassy",
      "podnoszą wiek emerytalny",
      "rżną głupa",
      "odbierają dzieci rodzicom",
      "wprowadzają absurdalne przepisy",
      "umieszczają dzieci w szkołach koedukacyjnych",
      "wprowadzają parytety",
      "nawołują do podniesienia podatków",
      "próbują wyrzucić kierowców z miast",
      "próbują skłócić Polske z Rosją",
      "głoszą brednie o globalnym ociepleniu",
      "zakazują posiadania broni",
      "nie dopuszczają prawicy do władzy",
      "uczą dzieci homoseksualizmu",
      "chcą dopuścić kobiety do władzy",
      "chcą dać kobietom prawa",
      "odbierają obywatelom prawo do obrony",
      "walczą o prawo do zawierania „homo-małżeństw”",
      "wprowadzają ustawy przez które miałoby się zabijać więcej nienarodzonych dzieci,",
      "chcą zniszczyć Porządek Cywilny",
    ],
    "i": [
      //dlaczego to robią
      "żeby poddawać wszystkich tresurze",
      "bo taka jest ich natura",
      "bo chcą wszystko kontrolować",
      "bo nie rozumieją, że socjalizm nie działa",
      "żeby wreszczie zapanował socjalizm",
      "dokładnie tak jak towarzysz Janosik",
      "zamiast pozwolić ludziom zarabiać",
      "żeby wyrwać kobiety z domu",
      "bo to jest w interesie tak zwanych ludzi pracy",
      "zamiast pozwolić decydować konsumentowi",
      "żeby nie opłacało sie mieć dzieci",
      "zamiast obniżyć podatki",
      "bo nie rozumieją, że selekcja naturalna jest czymś dobrym",
      "żeby mężczyźni przestali być agresywni",
      "bo dzięki temu mogą kraść",
      "bo dostają za to pieniądze",
      "bo tak sie uczy w państwowej szkole",
      "bo bez tego (tfu!) demokracja nie może istnieć",
      "bo głupich jest więcej niż mądrych",
      "bo chcą stworzyć raj na ziemii",
      "bo chcą zniszczyć cywilizacje białego człowieka",
      "bo takie jest prawo czarnego rynku",
      "bo nie widzą świata takim jaki jest,tylko takim jakim im go pokażą",
      "bo na tym polega liberalizm.",
      "Żeby nas potem powybierać jak ryby z saka",
      "aby obniżyć poziom edukacji",
      "bo chcą Prawa Człowieka na ich korzyść",
      "ponieważ natężenie mikkofobii na linijkę przekroczyło normy europejskie",
    ],
    "s": [
      //zakończenie
      "co ma zresztą tyle samo sensu, co zawody w szachach dla debili.",
      "co zostało dokładnie zaplanowane w Magdalence przez świętej pamięci Genereała Kiszczaka.",
      "i trzeba być idiotą, żeby ten system popierać.",
      "ale nawet ja jeszcze dożyje normalnych czasów.",
      "co dowodzi, że wyskrobano nie tych, co trzeba.",
      "a zwykłym ludziom wmawiają że im coś \"dadzą\".",
      "- cóż: chcieliście - tfu! - demokracji to macie.",
      "dlatego trzeba zlikwidować koryto a nie zmieniać świnie.",
      "a wystarczyłoby przestać wypłacać zasiłki.",
      "podczas gdy biali ludzie uważani są za dziwaków.",
      "co w wieku XIX po prostu by wyśmiano.",
      "- dlatego w społeczeństwie jest równość, a powinno być rozwarstwienie.",
      "ale w wolnej Polsce pójdą siedzieć.",
      "przez kolejne kadencje.",
      "o czym sie nie mówi.",
      "i dlatego właśnie Europa umiera.",
      "ale przyjdą muzułmanie i zrobią porządek.",
      "- tak samo zresztą jak za Hitlera.",
      "- prosze zobaczyć, co sie dzieje na Zachodzie, jeśli państwo nie wierzą.",
      "co lat temu sto nikomu nie przyszłoby do głowy.",
      "Lud jest głupi jak but z lewej stopy.",
      "jest dużo bardziej zasadne niż edukacja seksualna młodzieży.",
      "a powinno być to z całą surowością karane.",
      "przed czym zresztą ostrzegaliśmy już w 1980 r.",
      "ale pamiętajmy, podobno każdy za młodu powinien być socjalistą, a potem mądrzeje.",
      "Trzeba być idiotą, żeby chcieć w takim ustroju żyć.",
      "ma to tyle-ż sensu, co kojarzenie chrześcijaństwa z wojnami krzyżowymi.",
      "jest to pewna ideologia, po stokroć groźniejsza niż całe Imperium Zła.",
      "a jutro posuną się o krok dalej.",
      "ale to oznacza, że Murzyni niedługo podbiją świat. I wyrżną nas.",
    ]
}